version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag <IMAGE_NAME> <ECR_URL>
  post_build:
    commands:
      - docker push 885121665536.dkr.ecr.us-east-1.amazonaws.com/youtube:latest
      - printf '[{"name":<TASK_DEFINITION_NAME>,"imageUri":"%s"}]' <ECR_URL> > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
